"""Third-party snapshot copies must not gate or source gpu-dev disk restores.

`CopySnapshot` carries the source snapshot's tags onto the copy, so a scanner
(e.g. Wiz) copying a gpu-dev snapshot produces one tagged `gpu-dev-user` +
`disk_name` that we did not author. Those copies must be ignored both when
deciding whether to wait for a pending snapshot and when picking a restore
source -- a completed copy winning `max(StartTime)` would silently restore
stale data.
"""

from datetime import datetime, timedelta, timezone
from unittest.mock import MagicMock

import pytest

NOW = datetime(2026, 8, 18, 18, 0, tzinfo=timezone.utc)


def _ours(snap_id, start, state="completed", snap_type="cancellation"):
    return {
        "SnapshotId": snap_id,
        "StartTime": start,
        "State": state,
        "Progress": "100%" if state == "completed" else "4%",
        "VolumeId": "vol-0abc123",
        "Description": f"gpu-dev {snap_type} snapshot for user@example.com (disk: default)",
        "Tags": [
            {"Key": "gpu-dev-user", "Value": "user@example.com"},
            {"Key": "disk_name", "Value": "default"},
            {"Key": "SnapshotType", "Value": snap_type},
        ],
    }


def _wiz_copy(snap_id, start, state="pending"):
    """A Wiz scanner copy: inherits our tags, has its own wiz_* markers."""
    return {
        "SnapshotId": snap_id,
        "StartTime": start,
        "State": state,
        "Progress": "4%" if state == "pending" else "100%",
        "VolumeId": "vol-ffffffff" if state == "pending" else "vol-0abc123",
        "Description": "auto-generated by Wiz",
        "Tags": [
            {"Key": "gpu-dev-user", "Value": "user@example.com"},
            {"Key": "disk_name", "Value": "default"},
            {"Key": "ManagedBy", "Value": "gpu-dev-cli"},
            {"Key": "wiz", "Value": "auto-gen-snapshot"},
            {"Key": "wiz_temp_resource_purpose", "Value": "copied-snapshot"},
        ],
    }


@pytest.fixture
def ec2(monkeypatch, lambda_index):
    client = MagicMock()
    client.describe_volumes.return_value = {"Volumes": []}
    client.create_volume.return_value = {"VolumeId": "vol-new"}
    monkeypatch.setattr(lambda_index, "ec2_client", client)
    return client


def _set_snapshots(ec2, pending, completed):
    ec2.describe_snapshots.return_value = {"Snapshots": pending}
    ec2.get_paginator.return_value.paginate.return_value = [{"Snapshots": completed}]


def _restore(lambda_index):
    return lambda_index.create_disk_from_snapshot_or_empty(
        "user@example.com", "us-east-2b", "default", "reservation-id"
    )


def test_pending_third_party_copy_does_not_block(ec2, lambda_index):
    """A pending Wiz copy is not ours -- it must not gate the reservation."""
    _set_snapshots(
        ec2,
        pending=[_wiz_copy("snap-wiz", NOW - timedelta(minutes=20))],
        completed=[_ours("snap-ours", NOW - timedelta(hours=1))],
    )

    volume_id, _, _ = _restore(lambda_index)

    assert volume_id == "vol-new"
    assert ec2.create_volume.call_args.kwargs["SnapshotId"] == "snap-ours"


def test_pending_snapshot_older_than_newest_completed_does_not_block(ec2, lambda_index):
    """Nothing to wait for when a newer completed snapshot already exists."""
    _set_snapshots(
        ec2,
        pending=[_ours("snap-stale", NOW - timedelta(hours=6), state="pending")],
        completed=[_ours("snap-fresh", NOW - timedelta(hours=1))],
    )

    volume_id, _, _ = _restore(lambda_index)

    assert volume_id == "vol-new"
    assert ec2.create_volume.call_args.kwargs["SnapshotId"] == "snap-fresh"


def test_pending_snapshot_newer_than_completed_still_blocks(ec2, lambda_index):
    """Regression guard: a genuine in-flight snapshot must still gate."""
    _set_snapshots(
        ec2,
        pending=[_ours("snap-inflight", NOW - timedelta(minutes=2), state="pending")],
        completed=[_ours("snap-old", NOW - timedelta(hours=5))],
    )

    with pytest.raises(lambda_index.SnapshotPendingError, match="snap-inflight"):
        _restore(lambda_index)


def test_completed_third_party_copy_not_used_as_restore_source(ec2, lambda_index):
    """A completed Wiz copy is newer but holds stale data -- never restore it."""
    _set_snapshots(
        ec2,
        pending=[],
        completed=[
            _ours("snap-ours", NOW - timedelta(hours=2)),
            _wiz_copy("snap-wiz", NOW - timedelta(minutes=10), state="completed"),
        ],
    )

    _restore(lambda_index)

    assert ec2.create_volume.call_args.kwargs["SnapshotId"] == "snap-ours"


def test_only_third_party_copies_means_empty_disk(ec2, lambda_index, aws_mocks):
    """With no snapshot of our own, fall back to an empty volume, not a copy."""
    _set_snapshots(
        ec2,
        pending=[],
        completed=[_wiz_copy("snap-wiz", NOW - timedelta(minutes=10), state="completed")],
    )
    # No snapshot of our own -> the clone-source lookup runs; it has none either.
    disks_table = MagicMock()
    disks_table.get_item.return_value = {"Item": {}}
    aws_mocks["dynamodb"].Table.return_value = disks_table

    _, is_new_disk, _ = _restore(lambda_index)

    assert is_new_disk is True
    assert "SnapshotId" not in ec2.create_volume.call_args.kwargs
